packages:
  - packages/*

onlyBuiltDependencies:
  - '@firebase/util'
  - '@swc/core'
  - '@valian/eslint-config'
  - nx
  - protobufjs
  - unrs-resolver

peerDependencyRules:
  allowAny:
    - storybook

publicHoistPattern:
  - vitest-mock-extended
  - '@sentry/core'
